### ISSUE TITLE
access to pattern (Surface and SurfaceConnectivity) in Volume

### ISSUE THREAD

**Issue by gloook** [ultimaille/ultimaille#30]
On peut accéder aux index locaux par:
reference_cells[Volume::TETRAHEDRON].vert(cf, 0)
est-ce qu'on pourrait pas y accéder via le volume ?
avec un truc du genre:
Tetrahedra::pattern_connectivity.vert(cf, 0)

**Comment by gloook** [comment]
Pourquoi ces fonctions ne prennent pas un id de facet en param?
vec3 Volume::Util::bary_facet(const int c, const int lf) const...
vec3 Volume::Util::facet_normal(const int c, const int lf) const...
Ca paraitrait plus logique, surtout si on n'itère pas systématiquement sur cells, puis localfacet (genre facet_iter ;) )

**Comment by gloook** [comment]
ah, et oui, pareil pour construire un halfedge

**Comment by ssloy** [comment]
j'ai l'impression que c'est pas mal obsolete de nos jours comme plainte... @gloook tu valides ?
