### ISSUE TITLE
connectivity reset error ?

### ISSUE THREAD

**Issue by gloook** [ultimaille/ultimaille#31]
Lorsqu'on fait un reset sur un fec, le "resize" change bien la taille, mais ne met à -1 que les nouveaux sommets/edges... j'ai l'impression qu'il faudrait faire un clear() avant, ou un fill() peut etre...
 
void SurfaceConnectivity::reset() {
        c2f.resize(m.ncorners(), -1);
        c2c.resize(m.ncorners(), -1);
        v2c.resize(m.nverts(),   -1);
.....

**Comment by ssloy** [comment]
valid complaint

**Comment by ssloy** [comment]
@gloook c pas resolu ça ?
