### ISSUE TITLE
missing UM namescape for marco

### ISSUE THREAD

**Issue by gloook** [ultimaille/ultimaille#44]
um_assert macro works only after
using namespace UM;

It would always work if adding "UM::" in lines 14 and 16 of assert.h:

#define CUR_SOURCE_LOCATION UM::source_location{__FILE__, __LINE__, __PRETTY_FUNCTION__}
#define CUR_SOURCE_LOCATION UM::source_location{__FILE__, __LINE__, __FUNCSIG__}

**Comment by ssloy** [comment]
fixed in https://github.com/ultimaille/ultimaille/commit/04e89a072e092465509d7e433c34f7b5e2163fb2
