### ISSUE TITLE
Add function to get a primitive from mesh

### ISSUE THREAD

**Issue by lbinria** [ultimaille/ultimaille#57]
Getting a primitive from mesh using constructors is verbose and non-intuitive, is it possible to consider adding a new function (sugar) that get primitive from mesh ?

`Surface::Vertex(m, v)` <=> `m.vertex(v)`
`Surface::Facet(m, f)` <=> `m.facet(f)`
...

**Comment by ssloy** [comment]
https://github.com/ultimaille/ultimaille/commit/6e0e03e033a69c032fda515c4f0202d3dfc17690
