### ISSUE TITLE
Load attributes of medit file format

### ISSUE THREAD

**Issue by lbinria** [ultimaille/ultimaille#71]
I'm converting `.step` format to `.mesh`, and I would be able to load `.mesh` attributes in ultimaille to do some computations. Here https://github.com/ultimaille/ultimaille/commit/1a197cd1781d55c45ca6440a40e7b82d0d675a34, you'll find a test that works, but if you're agree with that, I have to modify the other functions that loads Surfaces, Volumes, etc.

**Comment by ssloy** [comment]
If I remember correctly, .mesh attributes are very limited as compared to, say, vtk. Won't .vtk be a better option?

**Comment by lbinria** [comment]
Yes, I think there is only one attribute possible (maybe more but I should test it) per primitive (points, edges, facets), however it's enough to retrieve important data from the `.step`.

`.step` to `.vtk` conversion is possible with the program I use, but attributes are not preserved...

Apart from that, I think it's great to be able to load attributes if there are any, but it's more a question of design choice :)

**Comment by ssloy** [comment]
Why not, but the writer should warn the user if user wants to store something that is not supported by .mesh

**Comment by lbinria** [comment]
See merge request #72
