### ISSUE TITLE
Create a neat namsespace for unsigned_area, tet_volume etc

### ISSUE THREAD

**Issue by ssloy** [ultimaille/ultimaille#82]
in primitive_geometry.h

1) not to pollute the global namespace UM::
2) to have an easier access to those specific geometric functions

**Comment by lbinria** [comment]
What do you think about an inner namespace named `geometry`, so you can access these functions using `UM::geometry`

**Comment by ssloy** [comment]
UM::GEO:: ?
By the way, should one or both of them be capitalized? => ask @gloook

**Comment by lbinria** [comment]
UM is an acronym it's normal for it to be capitalized. However, naming convention for namespace can differ, CamlCase or snake_case can be used, but I don't see any namespace in full capitalized (apart from acronyms).
`UM::geo` or `UM:Geo` ?

**Comment by ssloy** [comment]
geo
